// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ2lOsQqV3VSQniaReilDn8cqVsweO38o',
    appId: '1:248239413837:web:0c322796e9f0b5c8b69a04',
    messagingSenderId: '248239413837',
    projectId: 'simple-plan-aea78',
    authDomain: 'simple-plan-aea78.firebaseapp.com',
    databaseURL: 'https://simple-plan-aea78-default-rtdb.firebaseio.com',
    storageBucket: 'simple-plan-aea78.firebasestorage.app',
    measurementId: 'G-YGTK3BGMTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmxzyi7zWW-VDfVR2qSfdmK6S4ACM_8Vg',
    appId: '1:248239413837:android:10076fd8258d1565b69a04',
    messagingSenderId: '248239413837',
    projectId: 'simple-plan-aea78',
    databaseURL: 'https://simple-plan-aea78-default-rtdb.firebaseio.com',
    storageBucket: 'simple-plan-aea78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsa8JC1eREer6hmUpWwC0M-oSkd39ADT0',
    appId: '1:248239413837:ios:ca654966e5f847a5b69a04',
    messagingSenderId: '248239413837',
    projectId: 'simple-plan-aea78',
    databaseURL: 'https://simple-plan-aea78-default-rtdb.firebaseio.com',
    storageBucket: 'simple-plan-aea78.firebasestorage.app',
    iosBundleId: 'com.example.simplePlan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsa8JC1eREer6hmUpWwC0M-oSkd39ADT0',
    appId: '1:248239413837:ios:ca654966e5f847a5b69a04',
    messagingSenderId: '248239413837',
    projectId: 'simple-plan-aea78',
    databaseURL: 'https://simple-plan-aea78-default-rtdb.firebaseio.com',
    storageBucket: 'simple-plan-aea78.firebasestorage.app',
    iosBundleId: 'com.example.simplePlan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ2lOsQqV3VSQniaReilDn8cqVsweO38o',
    appId: '1:248239413837:web:f9b00f2a7a77efb7b69a04',
    messagingSenderId: '248239413837',
    projectId: 'simple-plan-aea78',
    authDomain: 'simple-plan-aea78.firebaseapp.com',
    databaseURL: 'https://simple-plan-aea78-default-rtdb.firebaseio.com',
    storageBucket: 'simple-plan-aea78.firebasestorage.app',
    measurementId: 'G-FPSJ1H4DX7',
  );

}